routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return view('admin');
});

Route::group(['middleware' => ['web']], function() {
  Route::resource('country','CountryController');  
});

Route::group(['middleware' => ['web']], function() {
  Route::resource('customer','CustomerController');  
});

Route::group(['middleware' => ['web']], function() {
  Route::resource('product','ProductController');  
});

Route::group(['middleware' => ['web']], function() {
  Route::resource('category','CategoryController');  
});

app/Country.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Country extends Model
{
    protected $table = 'countries';
}

app/Http/Controllers/CountryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Country;
use App\Customer;

class CountryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $countries = Country::all();
        
        return view('country.index', ['countries' => $countries]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $countries = Country::all();
        return view('country.create', ['countries' => $countries]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        
        $this->validate($request,[
        'code'=> 'required',
        'name' => 'required',
        'latitude'=> 'required',
        'longitude' => 'required',
        'shippingcostmultiplier'=> 'required'
        ]);
        
        
        
        $country = new Country;
        $country->code = $request->code;
        $country->name = $request->name;
        $country->latitude = $request->latitude;
        $country->longitude = $request->longitude;
        $country->shippingcostmultiplier = $request->shippingcostmultiplier;
        $country->save();
        
        return redirect()->route('country.index')->with('alert-success','Nieuw land opgeslaan!');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $country = Country::find($id);
        $countries = Country::all();
        
        return view('country.show',['country' => $country, 'countries' => $countries]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $countries = Country::all();
        $country = Country::find($id);
        return view('country.edit', array('country'=> $country, 'countries'=>$countries));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[
        'code'=> 'required',
        'name' => 'required',
        'latitude'=> 'required',
        'longitude' => 'required',
        'shippingcostmultiplier'=> 'required'
        ]);

        $country = Country::findOrFail($id);
        $country->code = $request->code;
        $country->name = $request->name;
        $country->latitude = $request->latitude;
        $country->longitude = $request->longitude;
        $country->shippingcostmultiplier = $request->shippingcostmultiplier;
        $country->save();

        return redirect()->route('country.index')->with('alert-success','Updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
     
    public function destroy($id)
    {
        // delete data
        
        $customers = Customer::where('idcountry', '=', $id)->first();
        
        
        if ($customers){
            return redirect()->route('country.index')->with('alert-danger', 'Land is gelinkt aan een klant');
        }
        else{
            $country = Country::findOrFail($id);
            $country->delete();
            return redirect()->route('country.index')->with('alert-success','Deleted');
        }
        
    }
}

resources/views/country/create.blade.php
@extends('master')
@section('content')
<div class="containter" style="width:80%;margin:auto;">
    <div class="row">
        <div class="col-md-9">
          <form class="" action="{{route('country.store')}}" method="post">
          {{csrf_field()}}
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="row" style="margin:4px;" >
                            <h3 class="col pull-left">Landen - Create</h3>
                            <div class="col pull-right">
                                <input type="submit" class="btn btn-success" value="Save">
                                <a href="{{route('country.index')}}" class="btn btn-warning">Cancel</a>
                            </div>
                     </div>
                </div>
            </div>
            
        
        <table class="table table-striped list-group">
          <tr>
              <td>
                <div class="form-group{{ ($errors->has('code')) ? $errors->first('code') : '' }}">
                  <label for="code">Code:</label>
                  <input type="text" name="code" class="form-control" placeholder="Enter code Here">
                  {!! $errors->first('code','<p class="help-block">:message</p>') !!}
                </div>
              </td>
          </tr>
          <tr>
              <td>
                <div class="form-group{{ ($errors->has('name')) ? $errors->first('name') : '' }}">
                  <label for="code">Naam:</label>
                  <input type="text" name="name" class="form-control" placeholder="Enter name Here">
                  {!! $errors->first('name','<p class="help-block">:message</p>') !!}
                </div>
              </td>
          </tr>
          
          <tr>
              <td>
                <div class="form-group{{ ($errors->has('latitude')) ? $errors->first('latitude') : '' }}">
                  <label for="code">Lengtegraad:</label>
                  <input type="text" name="latitude" class="form-control" placeholder="Enter latitude Here">
                  {!! $errors->first('latitude','<p class="help-block">:message</p>') !!}
                </div>
              </td>
          </tr>
          
          <tr>
              <td>
                <div class="form-group{{ ($errors->has('longitude')) ? $errors->first('longitude') : '' }}">
                  <label for="code">Breedtegraad:</label>
                  <input type="text" name="longitude" class="form-control" placeholder="Enter longitude Here">
                  {!! $errors->first('longitude','<p class="help-block">:message</p>') !!}
                </div>
              </td>
          </tr>
          
          <tr>
              <td>
                <div class="form-group{{ ($errors->has('shippingcostmultiplier')) ? $errors->first('shippingcostmultiplier') : '' }}">
                  <label for="code">Verzendkosten:</label>
                  <input type="text" name="shippingcostmultiplier" class="form-control" placeholder="Enter shippingcostmultiplier Here">
                  {!! $errors->first('shippingcostmultiplier','<p class="help-block">:message</p>') !!}
                </div>
              </td>
          </tr>
          
        </table>
        
      </form>
        </div>
        
        <div class ="row">
            <div class="col-md-3 col pull-right">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <table class="table table-striped list-group">
                            <tr>
                                <td>Land</td>
                                <td>Acties</td>
                            </tr>
                            @foreach($countries as $item)
                            <tr>
                                <td>{{$item->name}}</td>
                                <td>
                                      <a href="{{route('country.show',$item->id)}}" class="btn btn-primary">Select</a> </form>
                                </td>
                            </tr>
                            @endforeach
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


@stop

resources/views/country/edit.blade.php
@extends('master')
@section('content')
<div class="containter" style="width:80%;margin:auto;">
    <div class="row">
        <div class="col-md-9">
          <form method="post" action="{{ route('country.update',$country->id) }}">
          {{csrf_field()}}
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="row" style="margin:4px;" >
                            <h3 class="col pull-left">Landen - Edit</h3>
                            <div class="col pull-right">
                                <input type="submit" class="btn btn-success" value="Save">
                                <a href="{{route('country.index')}}" class="btn btn-warning">Cancel</a>
                            </div>
                     </div>
                </div>
            </div>
            
        <input type="hidden" name="_method" value="PUT">
        <table class="table table-striped list-group">
          <tr>
              <td>
                    <label for="code">Code:</label>
                    <input type="text" class="form-control" id="code" name="code" value="{{$country->code}}">
            
              </td>
          </tr>
          <tr>
              <td>
                    <label for="name">Naam:</label>
                    <input type="text" class="form-control" id="name" name="name" value="{{$country->name}}">
            
              </td>
          </tr>
          
          <tr>
              <td>
                    <label for="longitude">Lengtegraad:</label>
                    <input type="text" class="form-control" id="longitude" name="longitude" value="{{$country->longitude}}">
              
              </td>
          </tr>
          
          <tr>
              <td>
                    <label for="latitude">Breedtegraad:</label>
                    <input type="text" class="form-control" id="latitude" name="latitude" value="{{$country->latitude}}">
               
              </td>
          </tr>
          
          <tr>
              <td>
                    <label for="shippingcostmultiplier">Verzendkosten:</label>
                    <input type="text" class="form-control" id="shippingcostmultiplier" name="shippingcostmultiplier" value="{{$country->shippingcostmultiplier}}">
               
              </td>
          </tr>
          
        </table>
        
      </form>
          <textarea rows="2" class="textarea" readonly>
        @if(count($errors) > 0)
            @foreach ($errors->all() as $error)
                {{$error}}
            @endforeach
        @endif
    </textarea>
        </div>
        
        <div class ="row">
            <div class="col-md-3 col pull-right">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <table class="table table-striped list-group">
                            <tr>
                                <td>Land</td>
                                <td>Acties</td>
                            </tr>
                            @foreach($countries as $item)
                            <tr>
                                <td>{{$item->name}}</td>
                                <td>
                                      <a href="{{route('country.show',$item->id)}}" class="btn btn-primary">Select</a> </form>
                                </td>
                            </tr>
                            @endforeach
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


@stop

resources/views/country/index.blade.php
@extends('master')
@section('content')
<div class="containter" style="width:80%;margin:auto;">
    <div class="row">
        <div class="col-md-9">
            
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="row" style="margin:4px;" >
                            <h3 class="col pull-left">Landen</h3>
                             <a href="{{route('country.create')}}" class="btn btn-primary col pull-right">Create</a>
                     </div>
                </div>
            </div>
            
           
        </div>
        
        <div class ="row">
            <div class="col-md-3 col pull-right">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <table class="table table-striped list-group">
                            <tr>
                                <td>Land</td>
                                <td>Acties</td>
                            </tr>
                            @foreach($countries as $item)
                            
                            <tr>
                                <td>{{$item->name}}</td>
                                <td>
                                      <a href="{{route('country.show',$item->id)}}" class="btn btn-primary">Select</a> </form>
                                </td>
                            </tr>
                            @endforeach
                        </table>
                    </div>
                </div>
            </div>
        </div>
            
    </div>
</div>


@stop

resources/views/country/show.blade.php
@extends('master')
@section('content')
<div class="containter" style="width:80%;margin:auto;">
    <div class="row">
        <div class="col-md-9">
            
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="row" style="margin:4px;" >
                            <h3 class="col pull-left">Landen</h3>
                            <div class="col pull-right">
                                <form class="" action="{{route('country.destroy',$country->id)}}" method="post">
                                  <input type="hidden" name="_method" value="delete">
                                  <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                  <a href="{{route('country.edit',$country->id)}}" class="btn btn-primary">Edit</a>
                                  <a href="{{route('country.create')}}" class="btn btn-primary">Create</a>
                                  <input type="submit" class="btn btn-danger" onclick="return confirm('Bent u zeker?');" name="name" value="Delete">
                                   <a href="{{route('country.index')}}" class="btn btn-warning">Cancel</a>
                                
                            </div>
                     </div>
                </div>
            </div>
            
            <table class="table table-striped list-group">
                <tr>
                    <td>
                        <label for="code">Code:</label>
                        <input type="text"  class="form-control" id="code" name="code" value="{{$country->code}}" readonly>
                    </td>
                </tr>
                <tr>
                    <td>
                        <label for="name">Naam:</label>
                        <input type="text" class="form-control"  id="name" name="name" value="{{$country->name}}" readonly>
                    </td>
                </tr>
                <tr>
                    <td>
                        <label for="longitude">Lengtegraad:</label>
                        <input type="text" class="form-control"  id="longitude" name="longitude" value="{{$country->longitude}}" readonly>
                    </td>
                </tr>
                <tr>
                    <td>
                    <label for="latitude">Breedtegraad:</label>
                    <input type="text" class="form-control"  id="latitude" name="latitude" value="{{$country->latitude}}" readonly>
                    </td>
                </tr>
                <tr>
                    <td>
                        <label for="shippingcostmultiplier">Verzendkosten:</label>
                        <input type="text" class="form-control"  id="shippingcostmultiplier" name="shippingcostmultiplier" value="{{$country->shippingcostmultiplier}}" readonly>
                    </td>
                </tr>
                
            </table>
            </form>
        </div>
        
        <div class ="row">
            <div class="col-md-3 col pull-right">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <table class="table table-striped list-group">
                            <tr>
                                <td>Land</td>
                                <td>Acties</td>
                            </tr>
                            @foreach($countries as $item)
                            <tr>
                                <td>{{$item->name}}</td>
                                <td>
                                      <a href="{{route('country.show',$item->id)}}" class="btn btn-primary">Select</a> </form>
                                </td>
                            </tr>
                            @endforeach
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


@stop