routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return view('admin');
});

Route::group(['middleware' => ['web']], function() {
  Route::resource('country','CountryController');  
});

Route::group(['middleware' => ['web']], function() {
  Route::resource('customer','CustomerController');  
});

Route::group(['middleware' => ['web']], function() {
  Route::resource('product','ProductController');  
});

Route::group(['middleware' => ['web']], function() {
  Route::resource('category','CategoryController');  
});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $table = 'products';
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Product;
use App\Category;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::all();
        return view('product.index', ['products' => $products]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        $products = Product::all();
        return view('product.create', ['categories' => $categories], ['products' => $products]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
        'name'=> 'required',
        'idcategory' => 'required'
        ]);
        
        
        $product = new Product;
        $product->description = $request->description;
        $product->name = $request->name;
        $product->price =  empty($request->price) ? null: $request->price;
        $product->shippingcost = empty($request->shippingcost) ? null: $request->shippingcost;
        $product->totalrating = empty($request->totalrating) ? null: $request->totalrating;
        $product->thumbnail = $request->thumbnail;
        $product->image = $request->image;
        $product->discountpercentage = empty($request->discountpercentage) ? null: $request->discountpercentage;
        $product->idcategory = $request->idcategory;
        $product->votes = empty($request->votes) ? null: $request->votes;
        $product->save();
        
        return redirect()->route('product.index')->with('alert-success','Nieuw product opgeslaan!');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $products = Product::all();
        $product = Product::find($id);
        $category = Category::find($product->idcategory);
        
        return view('product.show',array(  'products'=>$products,
                                            'product'=>$product,
                                            'category'=>$category));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $products = Product::all();
        $product = Product::find($id);
        $categories = Category::all();
        return view('product.edit', array('product'=> $product, 'products'=>$products, 'categories' =>$categories));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        
        $this->validate($request,[
        'name'=> 'required',
        'idcategory' => 'required'
        ]);
        
        
        $product = Product::findOrFail($id);
        $product->description = $request->description;
        $product->name = $request->name;
        $product->price =  empty($request->price) ? null: $request->price;
        $product->shippingcost = empty($request->shippingcost) ? null: $request->shippingcost;
        $product->totalrating = empty($request->totalrating) ? null: $request->totalrating;
        $product->thumbnail = $request->thumbnail;
        $product->image = $request->image;
        $product->discountpercentage = empty($request->discountpercentage) ? null: $request->discountpercentage;
        $product->idcategory = $request->idcategory;
        $product->votes = empty($request->votes) ? null: $request->votes;
        $product->save();
        
        return redirect()->route('product.index')->with('alert-success','Updated');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $product = Product::findOrFail($id);
        $product->delete();
        return redirect()->route('product.index')->with('alert-success','Deleted');
    }
}

resources/views/product/create.blade.php
@extends('master')
@section('content')
<div class="containter" style="width:80%;margin:auto;">
    <div class="row">
        <div class="col-md-9">
          <form class="" action="{{route('product.store')}}" method="post">
          {{csrf_field()}}
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="row" style="margin:4px;" >
                            <h3 class="col pull-left">Producten - Create</h3>
                            <div class="col pull-right">
                                <input type="submit" class="btn btn-success" value="Save">
                                <a href="{{route('product.index')}}" class="btn btn-warning">Cancel</a>
                            </div>
                     </div>
                </div>
            </div>
            
        
        <table class="table table-striped list-group">
                   <tr><td>
              <label for="name">Naam:</label>
              <input type="text" class="form-control" id="name" name="name">
          </td></tr>
          <tr><td>
              <label for="description">Omschrijving:</label>
              <input type="text" class="form-control" id="description" name="description">
          </td></tr>
          <tr><td>
              <label for="price">Prijs:</label>
              <input type="text" class="form-control" id="price" name="price">
          </td></tr>
          <tr><td>
              <label for="shippingcost">Verzendkosten:</label>
              <input type="text" class="form-control" id="shippingcost" name="shippingcost">
          </td></tr>
          <tr><td>
              <label for="totalrating">Totaal rating:</label>
              <input type="text" class="form-control" id="totalrating" name="totalrating">
          </td></tr>
          <tr><td>
              <label for="thumbnail">Miniatuur:</label>
              <input type="text" class="form-control" id="thumbnail" name="thumbnail">
          </td></tr>
          <tr><td>
              <label for="image">Afbeelding:</label>
              <input type="text" class="form-control" id="image" name="image">
          </td></tr>
          <tr><td>
              <label for="discountpercentage">Aanbeidingspercent:</label>
              <input type="text" class="form-control" id="discountpercentage" name="discountpercentage">
          </td></tr>
          
          <tr><td>
              <label for="votes">Stemmen:</label>
              <input type="text" class="form-control" id="votes" name="votes">
          </td></tr>
          
          <tr><td>
              <label for="idcategory">Categorie:</label>
              <select id="idcategory" class="form-control" name="idcategory">
                  @foreach ($categories as $item)
                      <option value="{{$item->id}}" >{{$item->name}}</option>
                  @endforeach
              </select>
          </td></tr>
          
        </table>
        
      </form>
        </div>
        
       <div class ="row">
            <div class="col-md-3 col pull-right">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <table class="table table-striped list-group">
                            <tr>
                                <td>Naam</td>
                                <td>Acties</td>
                            </tr>
                            @foreach($products as $item)
                            <tr>
                                <td>{{$item->name}}</td>
                                <td>
                                      <a href="{{route('product.show',$item->id)}}" class="btn btn-primary">Select</a> </form>
                                </td>
                            </tr>
                            @endforeach
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


@stop

resources/views/product/edit.blade.php
@extends('master')
@section('content')
<div class="containter" style="width:80%;margin:auto;">
    <div class="row">
        <div class="col-md-9">
          <form class="" action="{{route('product.update', $product->id)}}" method="post">
          {{csrf_field()}}
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="row" style="margin:4px;" >
                            <h3 class="col pull-left">Producten - Edit</h3>
                            <div class="col pull-right">
                                <input type="submit" class="btn btn-success" value="Save">
                                <a href="{{route('product.index')}}" class="btn btn-warning">Cancel</a>
                            </div>
                     </div>
                </div>
            </div>
            
         <input type="hidden" name="_method" value="PUT">
        <table class="table table-striped list-group">
                 <tr><td>
              <label for="name">Naam:</label>
              <input type="text" class="form-control" id="name" name="name" value="{{$product->name}}">
          </td></tr>
          <tr><td>
              <label for="description">Omschrijving:</label>
              <input type="text" class="form-control" id="description" name="description" value="{{$product->description}}">
          </td></tr>
          <tr><td>
              <label for="price">Prijs:</label>
              <input type="text" class="form-control" id="price" name="price" value="{{$product->price}}">
          </td></tr>
          <tr><td>
              <label for="shippingcost">Verzendkosten:</label>
              <input type="text" class="form-control" id="shippingcost" name="shippingcost" value="{{$product->shippingcost}}">
          </td></tr>
          <tr><td>
              <label for="totalrating">Totaal rating:</label>
              <input type="text" class="form-control" id="totalrating" name="totalrating" value="{{$product->totalrating}}">
          </td></tr>
          <tr><td>
              <label for="thumbnail">Miniatuur:</label>
              <input type="text" class="form-control" id="thumbnail" name="thumbnail" value="{{$product->thumbnail}}">
          </td></tr>
          <tr><td>
              <label for="image">Afbeelding:</label>
              <input type="text" class="form-control" id="image" name="image" value="{{$product->image}}">
          </td></tr>
          <tr><td>
              <label for="discountpercentage">Aanbeidingspercent:</label>
              <input type="text" class="form-control" id="discountpercentage" name="discountpercentage" value="{{$product->discountpercentage}}">
          </td></tr>
          
          <tr><td>
              <label for="votes">Stemmen:</label>
              <input type="text" class="form-control" id="votes" name="votes" value="{{$product->votes}}">
          </td></tr>
          
          <tr><td>
              <label for="idcategory">Categorie:</label>
              <select id="idcategory" class="form-control" name="idcategory">
                  @foreach ($categories as $item)
                  
                      <option 
                      @if($product->idcategory == $item->id)
                          selected="selected"
                      @endif value="{{$item->id}}" >
                      {{$item->name}}
                      </option>
                      
                  @endforeach
              </select>
          </td></tr>
          </table>
          
      </form>
      <textarea rows="2"  class="form-control" class="textarea" readonly>
          @if(count($errors) > 0)
              @foreach ($errors->all() as $error)
                  {{$error}}
              @endforeach
          @endif
      </textarea>
        </div>
        
       <div class ="row">
            <div class="col-md-3 col pull-right">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <table class="table table-striped list-group">
                            <tr>
                                <td>Land</td>
                                <td>Acties</td>
                            </tr>
                            @foreach($products as $item)
                            <tr>
                                <td>{{$item->name}}</td>
                                <td>
                                      <a href="{{route('product.show',$item->id)}}" class="btn btn-primary">Select</a> </form>
                                </td>
                            </tr>
                            @endforeach
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


@stop

resources/views/product/index.blade.php
@extends('master')
@section('content')
<div class="containter" style="width:80%;margin:auto;">
    <div class="row">
        <div class="col-md-9">
            
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="row" style="margin:4px;" >
                            <h3 class="col pull-left">Producten</h3>
                             <a href="{{route('product.create')}}" class="btn btn-primary col pull-right">Create</a>
                     </div>
                </div>
            </div>
        </div>
        
        <div class ="row">
            <div class="col-md-3 col pull-right">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <table class="table table-striped list-group">
                            <tr>
                                <td>Naam</td>
                                <td>Acties</td>
                            </tr>
                            @foreach($products as $item)
                            
                            <tr>
                                <td>{{$item->name}}</td>
                                <td>
                                      <a href="{{route('product.show',$item->id)}}" class="btn btn-primary">Select</a> </form>
                                </td>
                            </tr>
                            @endforeach
                        </table>
                    </div>
                </div>
            </div>
        </div>
            
    </div>
</div>


@stop

resources/views/product/show.blade.php
@extends('master')
@section('content')
<div class="containter" style="width:80%;margin:auto;">
    <div class="row">
        <div class="col-md-9">
            
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="row" style="margin:4px;" >
                            <h3 class="col pull-left">Producten</h3>
                            <div class="col pull-right">
                                <form class="" action="{{route('product.destroy',$product->id)}}" method="post">
                                  <input type="hidden" name="_method" value="delete">
                                  <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                  <a href="{{route('product.edit',$product->id)}}" class="btn btn-primary">Edit</a>
                                  <a href="{{route('product.create')}}" class="btn btn-primary">Create</a>
                                  <input type="submit" class="btn btn-danger" onclick="return confirm('Bent u zeker?');" name="name" value="Delete">
                                   <a href="{{route('product.index')}}" class="btn btn-warning">Cancel</a>
                                </form>
                            </div>
                     </div>
                </div>
            </div>
            
            <table class="table table-striped list-group">
          <tr><td>
              <label for="name">Naam:</label>
              <input type="text" class="form-control" id="name" name="name" value="{{$product->name}}" readonly>
          </td></tr>
          <tr><td>
              <label for="description">Omschrijving:</label>
              <input type="text" class="form-control" id="description" name="description" value="{{$product->description}}" readonly>
          </td></tr>
          <tr><td>
              <label for="price">Prijs:</label>
              <input type="text" class="form-control" id="price" name="price" value="{{$product->price}}" readonly>
          </td></tr>
          <tr><td>
              <label for="shippingcost">Verzendkosten:</label>
              <input type="text" class="form-control" id="shippingcost" name="shippingcost" value="{{$product->shippingcost}}" readonly>
          </td></tr>
          <tr><td>
              <label for="totalrating">Totaal rating:</label>
              <input type="text" class="form-control" id="totalrating" name="totalrating" value="{{$product->totalrating}}" readonly>
          </td></tr>
          <tr><td>
              <label for="thumbnail">Miniatuur:</label>
              <input type="text" class="form-control" id="thumbnail" name="thumbnail" value="{{$product->thumbnail}}" readonly>
          </td></tr>
          <tr><td>
              <label for="image">Afbeelding:</label>
              <input type="text" class="form-control" id="image" name="image" value="{{$product->image}}" readonly>
          </td></tr>
          <tr><td>
              <label for="discountpercentage">Aanbeidingspercent:</label>
              <input type="text" class="form-control" id="discountpercentage" name="discountpercentage" value="{{$product->discountpercentage}}" readonly>
          </td></tr>
          
          <tr><td>
              <label for="votes">Stemmen:</label>
              <input type="text" class="form-control" id="votes" name="votes" value="{{$product->$product}}" readonly>
          </td></tr>
          
          <tr><td>
              <label for="idcategory">Categorie:</label>
              <select id="idcategory" class="form-control" name="idcategory" value="{{$category->name}}" readonly>
              </select>
          </td></tr>
                
            </table>
            </form>
        </div>
        
        <div class ="row">
            <div class="col-md-3 col pull-right">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <table class="table table-striped list-group">
                            <tr>
                                <td>Land</td>
                                <td>Acties</td>
                            </tr>
                            @foreach($products as $item)
                            <tr>
                                <td>{{$item->name}}</td>
                                <td>
                                      <a href="{{route('product.show',$item->id)}}" class="btn btn-primary">Select</a> </form>
                                </td>
                            </tr>
                            @endforeach
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@stop