routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return view('admin');
});

Route::group(['middleware' => ['web']], function() {
  Route::resource('country','CountryController');  
});

Route::group(['middleware' => ['web']], function() {
  Route::resource('customer','CustomerController');  
});

Route::group(['middleware' => ['web']], function() {
  Route::resource('product','ProductController');  
});

Route::group(['middleware' => ['web']], function() {
  Route::resource('category','CategoryController');  
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $table = 'categories';
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Category;
use App\Product;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::all();
        return view('category.index', ['categories' => $categories]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        return view('category.create', ['categories' => $categories]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate
        (
            $request, 
            ['description' => 'max:1024',
            'name' => 'required|max:255']
        );
        
        $category = new Category();
        $category->name = $request->name;
        $category->description = $request->description;
        $category->save();
        
        return redirect()->route('category.index')->with('alert-success','Nieuwe categorie opgeslaan!');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $categories = Category::all();
        $category = Category::find($id);
        return view('category.show',array('category'=>$category, 'categories'=>$categories));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $categories = Category::all();
        $category = Category::find($id);
        return view('category.edit', array('category'=> $category, 'categories'=>$categories));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate
        (
            $request, 
            ['name' => 'required|max:255']
        );
        
        $category = Category::find($id);
        $category->Name = $request->input('name');
        $category->Description = $request->input('description');
        $category->save();
        
        
        return redirect()->route('category.index')->with('alert-success','Updated!');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        
        $producten = Product::where('idcategory', '=', $id)->first();
        
        
        if ($producten){
            return redirect()->route('category.index')->with('alert-danger', 'Category is gelinkt aan een product');
        }
        else{
            $category = Category::findOrFail($id);
            $category->delete();
            return redirect()->route('category.index')->with('alert-success','Deleted');
        }
        
    }
}

resources/views/category/create.blade.php
@extends('master')
@section('content')
<div class="containter" style="width:80%;margin:auto;">
    <div class="row">
        <div class="col-md-9">
          <form class="" action="{{route('category.store')}}" method="post">
          {{csrf_field()}}
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="row" style="margin:4px;" >
                            <h3 class="col pull-left">Categorie - Create</h3>
                            <div class="col pull-right">
                                <input type="submit" class="btn btn-success" value="Save">
                                <a href="{{route('category.index')}}" class="btn btn-warning">Cancel</a>
                            </div>
                     </div>
                </div>
            </div>
            
        
        <table class="table table-striped list-group">
          <tr>
              <td>
                <div class="form-group{{ ($errors->has('name')) ? $errors->first('name') : '' }}">
                  <label for="name">Naam:</label>
                  <input type="text" name="name" class="form-control" placeholder="Enter name Here">
                  {!! $errors->first('name','<p class="help-block">:message</p>') !!}
                </div>
              </td>
          </tr>
          <tr>
              <td>
                <div class="form-group{{ ($errors->has('description')) ? $errors->first('description') : '' }}">
                  <label for="description">Omschrijving:</label>
                  <input type="text" name="description" class="form-control" placeholder="Enter description Here">
                  {!! $errors->first('description','<p class="help-block">:message</p>') !!}
                </div>
              </td>
          </tr>
          
        </table>
        
      </form>
        </div>
        
        <div class ="row">
            <div class="col-md-3 col pull-right">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <table class="table table-striped list-group">
                            <tr>
                                <td>Naam</td>
                                <td>Acties</td>
                            </tr>
                            @foreach($categories as $item)
                            <tr>
                                <td>{{$item->name}}</td>
                                <td>
                                      <a href="{{route('category.show',$item->id)}}" class="btn btn-primary">Select</a> </form>
                                </td>
                            </tr>
                            @endforeach
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


@stop

resources/views/category/edit.blade.php
@extends('master')
@section('content')
<div class="containter" style="width:80%;margin:auto;">
    <div class="row">
        <div class="col-md-9">
          <form method="post" action="{{ route('category.update',$category->id) }}">
          {{csrf_field()}}
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="row" style="margin:4px;" >
                            <h3 class="col pull-left">Category - Edit</h3>
                            <div class="col pull-right">
                                <input type="submit" class="btn btn-success" value="Save">
                                <a href="{{route('category.index')}}" class="btn btn-warning">Cancel</a>
                            </div>
                     </div>
                </div>
            </div>
            
        <input type="hidden" name="_method" value="PUT">
        <table class="table table-striped list-group">
          <tr>
              <td>
                    <label for="name">Naam:</label>
                    <input type="text" class="form-control" id="name" name="name" value="{{$category->name}}">
              </td>
          </tr>
          <tr>
              <td>
                    <label for="description">Omschrijving:</label>
                    <input type="text" class="form-control" id="description" name="description" value="{{$category->description}}">
              </td>
          </tr>
          
        </table>
        
      </form>
          <textarea rows="2" class="textarea" readonly>
        @if(count($errors) > 0)
            @foreach ($errors->all() as $error)
                {{$error}}
            @endforeach
        @endif
    </textarea>
        </div>
        
        <div class ="row">
            <div class="col-md-3 col pull-right">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <table class="table table-striped list-group">
                            <tr>
                                <td>Naam</td>
                                <td>Acties</td>
                            </tr>
                            @foreach($categories as $item)
                            <tr>
                                <td>{{$item->name}}</td>
                                <td>
                                      <a href="{{route('category.show',$item->id)}}" class="btn btn-primary">Select</a> </form>
                                </td>
                            </tr>
                            @endforeach
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


@stop

resources/views/category/index.blade.php
@extends('master')
@section('content')
<div class="containter" style="width:80%;margin:auto;">
    <div class="row">
        <div class="col-md-9">
            
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="row" style="margin:4px;" >
                            <h3 class="col pull-left">Categorie</h3>
                             <a href="{{route('category.create')}}" class="btn btn-primary col pull-right">Create</a>
                     </div>
                </div>
            </div>
            
        </div>
        
        <div class ="row">
            <div class="col-md-3 col pull-right">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <table class="table table-striped list-group">
                            <tr>
                                <td>Naam</td>
                                <td>Acties</td>
                            </tr>
                            @foreach($categories as $item)
                            <tr>
                                <td>{{$item->name}}</td>
                                <td>
                                      <a href="{{route('category.show',$item->id)}}" class="btn btn-primary">Select</a> </form>
                                </td>
                            </tr>
                            @endforeach
                        </table>
                    </div>
                </div>
            </div>
        </div>
            
    </div>
</div>


@stop

resources/views/category/show.blade.php
@extends('master')
@section('content')
<div class="containter" style="width:80%;margin:auto;">
    <div class="row">
        <div class="col-md-9">
            
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="row" style="margin:4px;" >
                            <h3 class="col pull-left">Categorie</h3>
                            <div class="col pull-right">
                                <form class="" action="{{route('category.destroy',$category->id)}}" method="post">
                                  <input type="hidden" name="_method" value="delete">
                                  <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                  <a href="{{route('category.edit',$category->id)}}" class="btn btn-primary">Edit</a>
                                  <a href="{{route('category.create')}}" class="btn btn-primary">Create</a>
                                  <input type="submit" class="btn btn-danger" onclick="return confirm('Bent u zeker?');" name="name" value="Delete">
                                   <a href="{{route('category.index')}}" class="btn btn-warning">Cancel</a>
                                </form>
                            </div>
                     </div>
                </div>
            </div>
            
            <table class="table table-striped list-group">
                <tr>
                    <td>
                        <label for="name">Naam:</label>
                    <input type="text" class="form-control"  id="name" name="name" value="{{$category->name}}" readonly>
                    </td>
                </tr>
                <tr>
                    <td>
                        <label for="description">Omschrijving:</label>
                    <input type="text"  class="form-control" id="description" name="description" value="{{$category->description}}" readonly>
                    </td>
                </tr>
            </table>
        </div>
        
         <div class ="row">
            <div class="col-md-3 col pull-right">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <table class="table table-striped list-group">
                            <tr>
                                <td>Naam</td>
                                <td>Acties</td>
                            </tr>
                            @foreach($categories as $item)
                            <tr>
                                <td>{{$item->name}}</td>
                                <td>
                                      <a href="{{route('category.show',$item->id)}}" class="btn btn-primary">Select</a> </form>
                                </td>
                            </tr>
                            @endforeach
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


@stop