routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return view('admin');
});

Route::group(['middleware' => ['web']], function() {
  Route::resource('country','CountryController');  
});

Route::group(['middleware' => ['web']], function() {
  Route::resource('customer','CustomerController');  
});

Route::group(['middleware' => ['web']], function() {
  Route::resource('product','ProductController');  
});

Route::group(['middleware' => ['web']], function() {
  Route::resource('category','CategoryController');  
});

app/Customer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Customer extends Model
{
    protected $table = 'customers';
    
}

app/Http/Controllers/CustomerController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Customer;
use App\Country;

class CustomerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //$customers = Customer::all()->join('countries', 'customer.idcountry', '=', 'country.id')->select('users.*', 'contacts.phone', 'orders.price')->get();
        //$customers = Customer::all();
        /*->join('countries', 'customer.idcountry', '=', 'country.id')->get()*/
        /*$customers = Customer::all();
        $i = 1;
        foreach($customers as $item)
        {
            $countries[$i] = Country::find($item->idcountry)->select('name');
            $i++;
        }*/
        
        $customers = Customer::all();
        return view('customer.index', ['customers' => $customers]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $customers = Customer::all();
        $countries = Country::all();
        return view('customer.create', ['countries' => $countries], ['customers' => $customers]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
        'nickname'=> 'required',
        'firstname' => 'required',
        'lastname'=> 'required',
        'address1' => 'required',
        'city'=> 'required',
        'postalcode' => 'required',
        'idcountry' => 'required'
        ]);
        
        
        $customer = new Customer;
        $customer->nickname = $request->nickname;
        $customer->firstname = $request->firstname;
        $customer->lastname = $request->lastname;
        $customer->address1 = $request->address1;
        $customer->address2 = $request->address2;
        $customer->city = $request->city;
        $customer->region = $request->region;
        $customer->postalcode = $request->postalcode;
        $customer->idcountry = $request->idcountry;
        $customer->phone = $request->phone;
        $customer->mobile = $request->mobile;
        $customer->save();
        
        return redirect()->route('customer.index')->with('alert-success','Nieuwe klant opgeslaan!');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $customers = Customer::all();
        $customer = Customer::find($id);
        $country = Country::find($customer->idcountry);
        
        return view('customer.show',array(  'customers'=>$customers,
                                            'customer'=>$customer,
                                            'country'=>$country));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $customers = Customer::all();
        $customer = Customer::find($id);
        $countries = Country::all();
        return view('customer.edit', array('customer'=> $customer, 'customers'=>$customers, 'countries' => $countries));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[
        'nickname'=> 'required',
        'firstname' => 'required',
        'lastname'=> 'required',
        'address1' => 'required',
        'city'=> 'required',
        'postalcode' => 'required',
        'idcountry' => 'required'
        ]);
        
        
        $customer = Customer::findOrFail($id);
        $customer->nickname = $request->nickname;
        $customer->firstname = $request->firstname;
        $customer->lastname = $request->lastname;
        $customer->address1 = $request->address1;
        $customer->address2 = $request->address2;
        $customer->city = $request->city;
        $customer->region = $request->region;
        $customer->postalcode = $request->postalcode;
        $customer->idcountry = $request->idcountry;
        $customer->phone = $request->phone;
        $customer->mobile = $request->mobile;
        $customer->save();
        
        return redirect()->route('customer.index')->with('alert-success','Updated!');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $customer = Customer::findOrFail($id);
        $customer->delete();
        return redirect()->route('customer.index')->with('alert-success','Deleted');
    }
}

resources/views/customer/create.blade.php
@extends('master')
@section('content')
<div class="containter" style="width:80%;margin:auto;">
    <div class="row">
        <div class="col-md-9">
          <form class="" action="{{route('customer.store')}}" method="post">
          {{csrf_field()}}
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="row" style="margin:4px;" >
                            <h3 class="col pull-left">Klanten - Create</h3>
                            <div class="col pull-right">
                                <input type="submit" class="btn btn-success" value="Save">
                                <a href="{{route('customer.index')}}" class="btn btn-warning">Cancel</a>
                            </div>
                     </div>
                </div>
            </div>
            
        
        <table class="table table-striped list-group">
          <tr><td>
              <label for="nickname">Roepnaam:</label>
              <input type="text" class="form-control" id="nickname" name="nickname">
          </td></tr>
          
          <tr><td>
              <label for="firstname">Voornaam:</label>
              <input type="text" class="form-control" id="firstname" name="firstname">
          </td></tr>
          
          <tr><td>
              <label for="lastname">Achternaam:</label>
              <input type="text" class="form-control" id="lastname" name="lastname">
          </td></tr>
          
          <tr><td>
              <label for="address1">Adres 1:</label>
              <input type="text" class="form-control" id="address1" name="address1">
          </td></tr>
          
          <tr><td>
              <label for="address2">Adres 2:</label>
              <input type="text" class="form-control" id="address2" name="address2">
          </td></tr>
          
          <tr><td>
              <label for="city">Stad:</label>
              <input type="text" class="form-control" id="city" name="city">
          </td></tr>
          
          <tr><td>
              <label for="region">Regio:</label>
              <input type="text" class="form-control" id="region" name="region">
          </td></tr>
          
          <tr><td>
              <label for="postalcode">Postcode:</label>
              <input type="text" class="form-control" id="postalcode" name="postalcode">
          </td></tr>
          
           <tr><td>
              <label for="idcountry">Land:</label>
              <select id="idcountry" class="form-control" name="idcountry">
                  @foreach ($countries as $item)
                      <option value="{{$item->id}}" >{{$item->name}}</option>
                  @endforeach
              </select>
          </td></tr>
          
          <tr><td>
              <label for="phone">Telefoon:</label>
              <input type="text" class="form-control" id="phone" name="phone">
          </td></tr>
           <tr><td>
              <label for="mobile">Mobieltje:</label>
              <input type="text" class="form-control" id="mobile" name="mobile">
          </td></tr>
        </table>
        
      </form>
        </div>
        
         <div class ="row">
            <div class="col-md-3 col pull-right">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <table class="table table-striped list-group">
                            <tr>
                                <td>Naam</td>
                                <td>Achternaam</td>
                                <td>Acties</td>
                            </tr>
                            @foreach($customers as $item)
                            
                            <tr>
                                <td>{{$item->firstname}}</td>
                                <td>{{$item->lastname}}</td>
                                <td>
                                      <a href="{{route('customer.show',$item->id)}}" class="btn btn-primary">Select</a>
                                </td>
                            </tr>
                            @endforeach
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


@stop

resources/views/customer/edit.blade.php
@extends('master')
@section('content')
<div class="containter" style="width:80%;margin:auto;">
    <div class="row">
        <div class="col-md-9">
          <form class="" action="{{route('customer.update', $customer->id)}}" method="post">
          {{csrf_field()}}
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="row" style="margin:4px;" >
                            <h3 class="col pull-left">Klanten - Edit</h3>
                            <div class="col pull-right">
                                <input type="submit" class="btn btn-success" value="Save">
                                <a href="{{route('customer.index')}}" class="btn btn-warning">Cancel</a>
                            </div>
                     </div>
                </div>
            </div>
            
        <input type="hidden" name="_method" value="PUT">
        <table class="table table-striped list-group">
          <tr><td>
              <label for="nickname">Roepnaam:</label>
              <input type="text" class="form-control" id="nickname" name="nickname" value="{{$customer->nickname}}">
          </div>
          <tr><td>
              <label for="firstname">Voornaam:</label>
              <input type="text" class="form-control" id="firstname" name="firstname" value="{{$customer->firstname}}">
          </div>
          <tr><td>
              <label for="lastname">Achternaam:</label>
              <input type="text" class="form-control" id="lastname" name="lastname" value="{{$customer->lastname}}">
          </td></tr>
          <tr><td>
              <label for="address1">Adres 1:</label>
              <input type="text" class="form-control" id="address1" name="address1" value="{{$customer->address1}}">
          </td></tr>
          <tr><td>
              <label for="address2">Adres 2:</label>
              <input type="text" class="form-control" id="address2" name="address2" value="{{$customer->address2}}">
          </td></tr>
          <tr><td>
              <label for="city">Stad:</label>
              <input type="text" class="form-control" id="city" name="city" value="{{$customer->city}}">
          </td></tr>
          <tr><td>
              <label for="region">Regio:</label>
              <input type="text" class="form-control" id="region" name="region" value="{{$customer->region}}">
          </td></tr>
          <tr><td>
              <label for="postalcode">Postcode:</label>
              <input type="text" class="form-control" id="postalcode" name="postalcode" value="{{$customer->postalcode}}">
          </td></tr>
          
          <tr><td>
              <label for="idcountry">Land:</label>
              <select id="idcountry" class="form-control" name="idcountry">
                  @foreach ($countries as $item)
                      <option 
                      @if($customer->idcountry == $item->id)
                          selected="selected"
                      @endif value="{{$item->id}}">
                      {{$item->Name}}
                      </option>
                  @endforeach
              </select>
          </td></tr>
          <tr><td>
              <label for="phone">Telefoon:</label>
              <input type="text" class="form-control" id="phone" name="phone" value="{{$customer->phone}}">
          </td></tr>
          <tr><td>
              <label for="mobile">Mobieltje:</label>
              <input type="text" class="form-control" id="mobile" name="mobile" value="{{$customer->mobile}}">
          </td></tr>
          
          </table>
          
      </form>
        </div>
        
         <div class ="row">
            <div class="col-md-3 col pull-right">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <table class="table table-striped list-group">
                            <tr>
                                <td>Naam</td>
                                <td>Achternaam</td>
                                <td>Acties</td>
                            </tr>
                            @foreach($customers as $item)
                            
                            <tr>
                                <td>{{$item->firstname}}</td>
                                <td>{{$item->lastname}}</td>
                                <td>
                                      <a href="{{route('customer.show',$item->id)}}" class="btn btn-primary">Select</a>
                                </td>
                            </tr>
                            @endforeach
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


@stop

resources/views/customer/index.blade.php
@extends('master')
@section('content')
<div class="containter" style="width:80%;margin:auto;">
    <div class="row">
        <div class="col-md-9">
            
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="row" style="margin:4px;" >
                            <h3 class="col pull-left">Klanten</h3>
                             <a href="{{route('customer.create')}}" class="btn btn-primary col pull-right">Create</a>
                     </div>
                </div>
            </div>
            
           
        </div>
        
        <div class ="row">
            <div class="col-md-3 col pull-right">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <table class="table table-striped list-group">
                            <tr>
                                <td>Naam</td>
                                <td>Achternaam</td>
                                <td>Acties</td>
                            </tr>
                            @foreach($customers as $item)
                            
                            <tr>
                                <td>{{$item->firstname}}</td>
                                <td>{{$item->lastname}}</td>
                                <td>
                                      <a href="{{route('customer.show',$item->id)}}" class="btn btn-primary">Select</a>
                                </td>
                            </tr>
                            @endforeach
                        </table>
                    </div>
                </div>
            </div>
        </div>
            
    </div>
</div>


@stop

resources/views/customer/show.blade.php
@extends('master')
@section('content')
<div class="containter" style="width:80%;margin:auto;">
    <div class="row">
        <div class="col-md-9">
            
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="row" style="margin:4px;" >
                            <h3 class="col pull-left">Klanten</h3>
                            <div class="col pull-right">
                                <form class="" action="{{route('customer.destroy',$customer->id)}}" method="post">
                                  <input type="hidden" name="_method" value="delete">
                                  <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                  <a href="{{route('customer.edit',$customer->id)}}" class="btn btn-primary">Edit</a>
                                  <a href="{{route('customer.create')}}" class="btn btn-primary">Create</a>
                                  <input type="submit" class="btn btn-danger" onclick="return confirm('Bent u zeker?');" name="name" value="Delete">
                                   <a href="{{route('customer.index')}}" class="btn btn-warning">Cancel</a>
                            </div>
                     </div>
                </div>
            </div>
            
            <table class="table table-striped list-group">
            <tr>
                <td>
                  <label for="nickname">Roepnaam:</label>
                  <input type="text" class="form-control" id="nickname" name="nickname" value="{{ $customer->nickname }}" readonly>
                  
                </td>
            </tr>
          
            <tr>
                <td>
              <label for="firstname">Voornaam:</label>
              <input type="text" class="form-control" id="firstname" name="firstname" value="{{ $customer->firstname }}" readonly>
                </td>
            </tr>
          
            <tr>
                <td>
              <label for="lastname">Achternaam:</label>
              <input type="text" class="form-control" id="lastname" name="lastname" value="{{ $customer->lastname }}" readonly>
                </td>
            </tr>
          
            <tr>
                <td>
              <label for="address1">Adres 1:</label>
              <input type="text" class="form-control" id="address1" name="address1" value="{{ $customer->address1 }}" readonly>
                </td>
            </tr>
          
            <tr>
                <td>
              <label for="address2">Adres 2:</label>
              <input type="text" class="form-control" id="address2" name="address2" value="{{ $customer->address2 }}" readonly>
                </td>
            </tr>
          
            <tr>
                <td>
              <label for="city">Stad:</label>
              <input type="text" class="form-control" id="city" name="city" value="{{ $customer->city }}" readonly>
                </td>
            </tr>
          
            <tr>
                <td>
              <label for="region">Regio:</label>
              <input type="text" class="form-control" id="region" name="region" value="{{ $customer->region }}" readonly>
                </td>
            </tr>
          
            <tr>
                <td>
              <label for="postalcode">Postcode:</label>
              <input type="text" class="form-control" id="postalcode" name="postalcode" value="{{ $customer->postalcode }}" readonly>
                </td>
            </tr>
            
            <tr>
                <td>
                    <label for="idcountry">Land:</label>
                    <input type="text" name="idcountry" id="idcountry" class="form-control" value="{{ $country->name }}" readonly>
                </td>
            </tr>
          
          <tr>
                    <td>
              <label for="phone">Telefoon:</label>
              <input type="text" class="form-control" id="phone" name="phone" value="{{ $customer->phone }}" readonly>
                </td>
            </tr>
            <tr>
                <td>
              <label for="mobile">Mobieltje:</label>
              <input type="text" class="form-control" id="mobile" name="mobile" value="{{ $customer->mobile }}" readonly>
                </td>
            </tr>
      </table>
      </form>
      
        </div>
        
        <div class ="row">
            <div class="col-md-3 col pull-right">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <table class="table table-striped list-group">
                            <tr>
                                <td>Naam</td>
                                <td>Achternaam</td>
                                <td>Acties</td>
                            </tr>
                            @foreach($customers as $item)
                            
                            <tr>
                                <td>{{$item->firstname}}</td>
                                <td>{{$item->lastname}}</td>
                                <td>
                                      <a href="{{route('customer.show',$item->id)}}" class="btn btn-primary">Select</a>
                                </td>
                            </tr>
                            @endforeach
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


@stop